language: cpp
script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - export CXX=g++4.8
  - export CC=gcc4.8
  - alias g++=g++4.8
  - alias gcc=gcc4.8
  - alias c++=g++4.8
  - alias cc=gcc4.8
  - g++ --version
  - make
  - out/jsb third-party/libxml/libxml.jsb
