language: cpp
compiler: clang
script:
  - wget http://launchpadlibrarian.net/151932048/libc6_2.17-0ubuntu5.1_i386.deb
  - sudo dpkg -i ipts libc6_2.17-0ubuntu5.1_i386.deb
  - chmod +x bin/jsb
  - bin/jsb third-party/libxml/libxml.jsb
