language: cpp
compiler: clang
script:
  - export CC=clang
  - export CXX=clang++
  - alias gcc=clang
  - alias g++=clang++
  - objdump -p bin/jsb | grep GLIBC
  - make
  - out/jsb jsb.jsb
  - out/jsb third-party/libxml/libxml.jsb
